FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y iproute2 iptables ca-certificates bash && \
    rm -rf /var/lib/apt/lists/*

COPY k3s /usr/local/bin/k3s
RUN chmod +x /usr/local/bin/k3s

RUN rm -rf /etc/rancher/k3s /var/lib/rancher/k3s /var/lib/kubelet

CMD ["bash", "-c", "while true; do sleep 1000; done"]




